version: '3'

services:

  # PaperMC
  papermc:
    restart: unless-stopped
    build:
      context: papermc
      dockerfile: Dockerfile
    volumes:
      - ./papermc:/app
      - /app/paper.jar
    ports:
      - 25565:25565
    environment:
      JAVA_OPTS: "-Xms1G -Xmx2G"

  # cloudflared daemon for Bluemap Web UI
  # cloudflared-bluemap:
  #   image: ghcr.io/milgradesec/cloudflared:latest
  #   user: root
  #   command: tunnel
  #   environment:
  #     - TUNNEL_HOSTNAME=bluemap-test.yude.jp
  #     - TUNNEL_URL=http://papermc:8100
  #     - TUNNEL_ORIGIN_CERT=/root/.cloudflared/cert.pem
  #   volumes:
  #     - '$HOME/.cloudflared:/root/.cloudflared'
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  #   restart: unless-stopped
  