version: '3.9'

services:

  # PaperMC
  papermc:
    build:
      context: papermc
      dockerfile: Dockerfile
      args:
        UID: 1000
        GID: 1000
        USERNAME: app
        GROUPNAME: app
    volumes:
      - ./papermc:/app
    tty: true
    stdin_open: true
    environment:
      JAVA_OPTS: "-Xms1G -Xmx2G"

  # Waterfall
  waterfall:
    build:
      context: waterfall
      dockerfile: Dockerfile
      args:
        UID: 1000
        GID: 1000
        USERNAME: app
        GROUPNAME: app
    volumes:
      - ./waterfall:/app
    tty: true
    stdin_open: true
    ports:
      - 25565:25565
    environment:
      JAVA_OPTS: "-Xms256M -Xmx512M"

  # cloudflared daemon for Bluemap Web UI
  cloudflared-bluemap:
    image: cloudflare/cloudflared:2022.3.4-amd64
    user: root
    command: tunnel
    environment:
      - TUNNEL_HOSTNAME=bluemap.yude.jp
      - TUNNEL_URL=http://papermc:8100
      - TUNNEL_ORIGIN_CERT=/root/.cloudflared/cert.pem
    volumes:
      - '$HOME/.cloudflared:/root/.cloudflared'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  # MariaDB for CoreProtect plugin on PaperMC
  coreprotect_db:
    restart: unless-stopped
    image: mariadb:10.5
    volumes:
      - ./db/data:/val/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/sql:/docker-entrypoint-initdb.d
      - ./db/log:/val/log/mysql
    environment:
        MYSQL_ROOT_PASSWORD: coreprotect
        MYSQL_DATABASE: coreprotect
        MYSQL_USER: coreprotect
        MYSQL_PASSWORD: coreprotect
        TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
